### ISSUE TITLE
Support classes and methods

### ISSUE THREAD

**Issue by romanzolotarev** [mdiebolt/clog#5]
Hi Matt, thank you for the `clog`. Do you think it's possible to split scores by classes and methods?

By the way here is a companion package for the `clog`: 
https://github.com/romanzolotarev/clog-top ;)

**Comment by mdiebolt** [comment]
Lately, I've been using https://github.com/clutchski/coffeelint for static analysis and ensuring consistent code style across the team. It has an option for cyclomatic complexity by method.

Unless there's a lot of demand for adding this to clog, it's not super high on my priority list since CoffeeLint already does a great job at this.
